name: Test and publish package

on:
  release:
    types: [created]

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Test package
        run: yarn test

      - name: Publish package
        run: npm publish
